### ISSUE TITLE
No current consumption?

### ISSUE THREAD

**Issue by Ogge66** [abeggled/com.northq#3]
Great to implement the northq power meter in homey! However I’m missing the current consumption. Can this be added, please?

**Comment by abeggled** [comment]
The NorthQ does not provide the current consumption, or I'm unaware of this, I'm using this device since about 5 years on different platofrms. The only way would be to calculate the "current" consumption bei taking kwh and time difference between two measurements and do some calc. But I'm unaware of getting the timestamps of reports within the driver.

**Comment by Ogge66** [comment]
But with my former smart home device “Telldus” I did get current consumption, maximum power consumption, total consumption etc.... 

Best regards
Oscar

**Comment by abeggled** [comment]
I don't say it's impossible, but it's not documented and in my opinion it's only possible by calculating as mentioned before. If you have some documentation how telldus did it, I'm happy to extend the app!

**Comment by Ogge66** [comment]
Are you swedish? In that case does this help you? 
https://www.automatiserar.se/test-av-northq-energimatare/

**Comment by Ogge66** [comment]
http://forum.micasaverde.com/index.php?topic=16082.0

**Comment by abeggled** [comment]
The micasa verde app does what I described earlier. Unfortunately, I currently see no way I can implement this in Homey.

**Comment by Ogge66** [comment]
I understand... Can I make a donation or something else to make it happen?

**Comment by abeggled** [comment]
Sorry it's not a question of money, it's a question of time :-(
I will do my best to find a solution.

Am Fr., 29. Juni 2018 um 12:18 Uhr schrieb Ogge66 <notifications@github.com
>:

> I understand... Can I make a donation or something else to make it happen?
>
> Sent from my iPhone
>

**Comment by Ogge66** [comment]
Thank you very much!

**Comment by abeggled** [comment]
Sorry, since I did'nt own a Homey anymore, I can't support you and my peace of software.
