### ISSUE TITLE
Can't include

### ISSUE THREAD

**Issue by joakim93** [abeggled/com.northq#4]
Hi, I can't include the power meter to homey. I have reset the power meter and the homey. The power meter enters inclusion mode but homey doesn't find it.

**Comment by abeggled** [comment]
What's the distance between Homey and the NorthQ meter during pairing?
What's the detailed message on Homey?

**Comment by joakim93** [comment]
about 20cm. How do I find the detailed message from homey? It doesn't say anything just says after a while that nothing found. Where do I find the logs?

**Comment by joakim93** [comment]
Any ideas?

**Comment by abeggled** [comment]
Sorry for the delay.
It seems you have a general pairing-problem.
Have you tried to reset the NorthQ-Meter (_By pressing the button 7 times the Power Reader will be reset to factory defaults._)
Try to add it again.
If Homey does not find your device, then your Homey or the device you trying to add has a problem. From the North-App perspective I can't help you in this situation.

**Comment by joakim93** [comment]
Okay I sent the northq meter back. So let's see if that was the problem. Thanks will let you know.

**Comment by joakim93** [comment]
I got it back and now it did include fine. Does this have any realtime logging?

**Comment by abeggled** [comment]
fine, not at the moment, please check issue #3
