### ISSUE TITLE
App for Homey 2.0?

### ISSUE THREAD

**Issue by PBTK** [abeggled/com.northq#5]
Any plans for an app supportiing homey 2.0?

**Comment by abeggled** [comment]
Are there any issues? If necessary, I will start adoption after the official 2.0 release have been published.

**Comment by PBTK** [comment]
No problem to add device and at connection a first value is read but then nothing updates.

**Comment by bk147** [comment]
> No problem to add device and at connection a first value is read but then nothing updates.

I'm experiencing the same behaviour :-(

**Comment by dizzypro** [comment]
> No problem to add device and at connection a first value is read but then nothing updates.

Same here, some settings seems to store, like wake up interval. But in device specific it times out.
Really appreciate you trying to make this app work.

**Comment by abeggled** [comment]
Thanks for the issues, I will have a look, but don't expect to much, as my primary device is on 1.5.13 and due the low Z-wave signal strength I can't use the North-Q as meter device. But I will try to find a solution, but doen't expect it soon, as I'm busy with a lot of work in my company and I'm actually planning my new house with KNX as bus-system. Homey and wireless-protocols will get a very low priority in this project.

**Comment by abeggled** [comment]
Sorry, since I did'nt own a Homey anymore, I can't support you and my peace of software.
